version: "3.9"

services:
  db:
    image: postgres:15
    container_name: air_quality_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    container_name: air_quality_api
    environment:
      - ENV=docker
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers"
    volumes:
      - ./app:/app/app
    restart: unless-stopped
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  postgres_data:

networks:
  backend:
